const listOfDiseases = [
    { 'value':  'enfermedad-celíaca', 'label': 'Enfermedad Celíaca' },
    { 'value':  'intolerancia-a-la-lactosa', 'label': 'Intolerancia a la Lactosa' },
    { 'value':  'alergia-al-maní', 'label': 'Alergia al Maní' },
    { 'value':  'alergia-a-los-frutos-secos', 'label': 'Alergia a los Frutos Secos' },
    { 'value':  'alergia-a-los-mariscos', 'label': 'Alergia a los Mariscos' },
    { 'value':  'alergia-al-pescado', 'label': 'Alergia al Pescado' },
    { 'value':  'diabetes-mellitus', 'label': 'Diabetes Mellitus' },
    { 'value':  'hipertensión-arterial', 'label': 'Hipertensión Arterial' },
    { 'value':  'enfermedad-renal-crónica', 'label': 'Enfermedad Renal Crónica' },
    { 'value':  'insuficiencia-hepática', 'label': 'Insuficiencia Hepática' },
    { 'value':  'sii', 'label': 'Síndrome de Intestino Irritable (SII)' },
    { 'value':  'gota', 'label': 'Gota' },
    { 'value':  'anemia-por-deficiencia-de-hierro', 'label': 'Anemia por Deficiencia de Hierro' },
    { 'value':  'hipotiroidismo', 'label': 'Hipotiroidismo' },
    { 'value':  'hipertiroidismo', 'label': 'Hipertiroidismo' },
    { 'value':  'pku', 'label': 'Fenilcetonuria (PKU)' },
    { 'value':  'galactosemia', 'label': 'Galactosemia' },
    { 'value':  'hiperlipidemia', 'label': 'Hiperlipidemia' },
    { 'value':  'enfermedad-de-crohn', 'label': 'Enfermedad de Crohn' },
    { 'value':  'colitis-ulcerosa', 'label': 'Colitis Ulcerosa' },
    { 'value':  'enfermedad-de-wilson', 'label': 'Enfermedad de Wilson' },
    { 'value':  'insuficiencia-suprarrenal', 'label': 'Insuficiencia Suprarrenal' },
    { 'value':  'intolerancia-a-la-fructosa', 'label': 'Intolerancia a la Fructosa' },
    { 'value':  'síndrome-metabólico', 'label': 'Síndrome Metabólico' },
    { 'value':  'hiperuricemia', 'label': 'Hiperuricemia' },
    { 'value':  'trastornos-de-la-vesícula-biliar', 'label': 'Trastornos de la Vesícula Biliar' },
    { 'value':  'síndrome-del-intestino-corto', 'label': 'Síndrome del Intestino Corto' },
    { 'value':  'cáncer', 'label': 'Cáncer' },
    { 'value':  'obesidad', 'label': 'Obesidad' },
    { 'value':  'dislipidemia', 'label': 'Dislipidemia' },
    { 'value':  'síndrome-de-dumping', 'label': 'Síndrome de Dumping' },
    { 'value':  'erge', 'label': 'Reflujo Gastroesofágico (ERGE)' },
    { 'value':  'migrañas', 'label': 'Migrañas' },
    { 'value':  'insuficiencia-pancreática-exocrina', 'label': 'Insuficiencia Pancreática Exocrina' },
    { 'value':  'síndrome-de-sjögren', 'label': 'Síndrome de Sjögren' },
    { 'value':  'fibrosis-quística', 'label': 'Fibrosis Quística' },
    { 'value':  'enfermedad-de-addison', 'label': 'Enfermedad de Addison' },
    { 'value':  'trastornos-de-la-alimentación', 'label': 'Trastornos de la Alimentación' },
    { 'value':  'enfermedad-de-lyme', 'label': 'Enfermedad de Lyme' },
    { 'value':  'alzheimer', 'label': 'Alzheimer' },
    { 'value':  'enfermedad-de-huntington', 'label': 'Enfermedad de Huntington' },
    { 'value':  'enfermedad-de-parkinson', 'label': 'Enfermedad de Parkinson' },
    { 'value':  'enfermedades-cardiovasculares', 'label': 'Enfermedades Cardiovasculares' },
    { 'value':  'insuficiencia-cardíaca', 'label': 'Insuficiencia Cardíaca' },
    { 'value':  'sop', 'label': 'Síndrome del Ovario Poliquístico (SOP)' },
    { 'value': 'otros', 'label': 'Otros' }
];


export default listOfDiseases;